name: spigot-rank-system
version: '1.0-SNAPSHOT'
main: org.radialo.spigotranksystem.RankSystemPlugin
api-version: '1.20'
authors: [RadiALo]
description: My rank system plugin!
commands:
  rank:
    description: Changes player rank!
  donate:
    description: Allow to (free) donate!
